server {
    listen 10.14.1.1:8080;
    root /home/jhelbig/Desktop/webserv/;
    allow GET HEAD;
    autoindex on;
    max_request_body 1048576;
    error_page 400 /error_pages/code_400.html;
    error_page 401 /error_pages/code_401.html;
    error_page 403 /error_pages/code_403.html;
    error_page 500 /error_pages/code_500.html;
    error_page 501 /error_pages/code_501.html;
    error_page 502 /error_pages/code_502.html;
    error_page 503 /error_pages/code_503.html;

    location / {
        index index.html;
    }
    
    location /upload/ {
        allow POST DELETE;
        max_request_body 10485760;
    }

    location /scripts/*.py {
        allow GET POST;
        cgi /usr/bin/python3;
    }

    location /scripts/*.sh {
        allow GET POST;
        cgi /bin/sh;
    }
}
