#pragma once

#define REASON_200 "OK"
#define REASON_201 "Created"
#define REASON_202 "Accepted"
#define REASON_204 "No Content"
#define REASON_301 "Moved Permanently"
#define REASON_302 "Moved Temporarily"
#define REASON_304 "Not Modified"
#define REASON_400 "Bad Request"
#define REASON_401 "Unauthorized"
#define REASON_403 "Forbidden"
#define REASON_404 "Not Found"
#define REASON_500 "Internal Server Error"
#define REASON_501 "Not Implemented"
#define REASON_502 "Bad Gateway"
#define REASON_503 "Service Unavailable"
